title=Groovy Resources
date=2015-08-22
type=page
status=published
~~~~~~

== Websites

++++
<div class="mdl-grid">
    <div class="mdl-cell mdl-cell--4-col">
        <div class="resource-card-square mdl-card mdl-shadow--2dp">
          <div class="mdl-card__title mdl-card--expand">
            <h2 class="mdl-card__title-text">groovy-lang.org</h2>
          </div>
          <div class="mdl-card__supporting-text">
            The home of Groovy!
          </div>
          <div class="mdl-card__actions mdl-card--border">
            <a class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect"
                href="http://www.groovy-lang.org/">
              Visit groovy-lang.org
            </a>
          </div>
        </div>
    </div>
    <div class="mdl-cell mdl-cell--4-col">
            <div class="resource-card-square mdl-card mdl-shadow--2dp">
              <div class="mdl-card__title mdl-card--expand">
                <h2 class="mdl-card__title-text">mr haki</h2>
              </div>
              <div class="mdl-card__supporting-text">
                A trove of Groovy code snippets!
              </div>
              <div class="mdl-card__actions mdl-card--border">
                <a class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect"
                    href="http://mrhaki.blogspot.com/search/label/Groovy">
                  Groovy posts
                </a>
              </div>
            </div>
     </div>
</div>
++++

== Groovy Tech

++++
<div class="mdl-grid">
    <div class="mdl-cell mdl-cell--4-col">
        <div class="resource-card-square mdl-card mdl-shadow--2dp">
          <div class="mdl-card__title mdl-card--expand">
            <h2 class="mdl-card__title-text">Awesome Groovy</h2>
          </div>
          <div class="mdl-card__supporting-text">
            A curated list of Groovy tech
          </div>
          <div class="mdl-card__actions mdl-card--border">
            <a class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect"
                href="https://github.com/kdabir/awesome-groovy">
              Visit awesome-groovy
            </a>
          </div>
        </div>
    </div>
</div>
++++

== Books
++++
<div class="mdl-grid">
    <div class="mdl-cell mdl-cell--4-col">
        <div class="resource-card-wide mdl-card mdl-shadow--2dp">
          <div class="mdl-card__title">
            <h2 class="mdl-card__title-text">Groovy in Action</h2>
          </div>
          <div class="mdl-card__supporting-text">
            Groovy in Action, Second Edition is a thoroughly revised, comprehensive guide to Groovy programming. It introduces Java developers to the dynamic features that Groovy provides, and shows how to apply Groovy to a range of tasks including building new apps, integration with existing code, and DSL development. Covers Groovy 2.4.
          </div>
          <div class="mdl-card__actions mdl-card--border">
            <a class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect" href="http://www.manning.com/koenig2/">
              Book site
            </a>
          </div>
        </div>
    </div>
    <div class="mdl-cell mdl-cell--4-col">
            <div class="resource-card-wide mdl-card mdl-shadow--2dp">
              <div class="mdl-card__title">
                <h2 class="mdl-card__title-text">The Groovy 2 Tutorial</h2>
              </div>
              <div class="mdl-card__supporting-text">
                The Groovy 2 Tutorial is a primer for those who are new to the Groovy language and want to know how Groovy works. Groovy is a great language for those who want the flexibility of a dynamic language and the support of the Java ecosystem. Groovy is also a key to unlocking a range of other great technologies including Gradle, Grails and Android development.
              </div>
              <div class="mdl-card__actions mdl-card--border">
                <a class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect" href="https://leanpub.com/groovytutorial/">
                  Book site
                </a>
              </div>
            </div>
        </div>
</div>
++++

== News
++++
<div class="mdl-grid">
    <div class="mdl-cell mdl-cell--4-col">
        <div class="resource-card-square mdl-card mdl-shadow--2dp">
          <div class="mdl-card__title mdl-card--expand">
            <h2 class="mdl-card__title-text">Groovy Weekly</h2>
          </div>
          <div class="mdl-card__supporting-text">
            Prepared by Guillaume Laforge and always brimming with news.
          </div>
          <div class="mdl-card__actions mdl-card--border">
            <a class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect"
                href="http://glaforge.appspot.com/category/Groovy%20Weekly">
              Visit groovy weekly
            </a>
          </div>
        </div>
    </div>
    <div class="mdl-cell mdl-cell--4-col">
        <div class="resource-card-square mdl-card mdl-shadow--2dp">
          <div class="mdl-card__title mdl-card--expand">
            <h2 class="mdl-card__title-text">Groovy Calamari</h2>
          </div>
          <div class="mdl-card__supporting-text">
            Groovy Calamari is a weekly curated publication full of interesting, relevant links about the Groovy Ecosystem.
          </div>
          <div class="mdl-card__actions mdl-card--border">
            <a class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect"
                href="http://groovycalamari.com/">
              Visit groovycalamari.com
            </a>
          </div>
        </div>
    </div>
    <div class="mdl-cell mdl-cell--4-col">
        <div class="resource-card-square mdl-card mdl-shadow--2dp">
          <div class="mdl-card__title mdl-card--expand">
            <h2 class="mdl-card__title-text">The Groovy Podcast</h2>
          </div>
          <div class="mdl-card__supporting-text">
            Peter, Ken and Baruch with the latest news from the Groovy sphere
          </div>
          <div class="mdl-card__actions mdl-card--border">
            <a class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect"
                href="https://github.com/pledbrook/groovypodcast">
              Show notes
            </a>
          </div>
        </div>
    </div>
</div>
++++
